language: python
#branches:
#  only:
#    - master

git:
  depth: false

matrix:
  include:
    - os: linux
      env:
        - GCC_VERSION=7
        - cmake_option="-DREPORTS_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx"
      dist: xenial
      sudo: required
      python: 3.6
    - os: linux
      env:
        - GCC_VERSION=7
        - cmake_options="-DREPORTS_ENABLE_MPI=OFF"
      dist: xenial
      sudo: required
      python: 3.6

    - os: linux
      env:
        - GCC_VERSION=7
        - cmake_option="-DREPORTS_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx"
      dist: xenial
      sudo: required
      python: 2.7
    - os: linux
      env:
        - GCC_VERSION=7
        - cmake_option="-DREPORTS_ENABLE_MPI=OFF"
      dist: xenial
      sudo: required
      python: 2.7

    - os: osx
      env:
        - cmake_option="-DREPORTS_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx"
      osx_image: xcode10.3
      language: generic
      python: 3.6
    - os: osx
      env:
        - cmake_option="-DREPORTS_ENABLE_MPI=OFF"
      osx_image: xcode10.3
      language: generic
      python: 3.6

    - os: osx
      env:
        - cmake_option="-DREPORTS_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx"
      osx_image: xcode10.3
      language: generic
      python: 2.7
    - os: osx
      env:
        - cmake_option="-DREPORTS_ENABLE_MPI=OFF"
      osx_image: xcode10.3
      language: generic
      python: 2.7

addons:
  homebrew:
    packages:
      - hdf5
      - openmpi
      - iltommi/brews/hdf5-parallel
  apt:
    packages:
      - g++-7
      - libhdf5-dev
      - libhdf5-openmpi-dev
      - hdf5-tools
      - libopenmpi-dev
      - openmpi-bin
    sources:
      - ubuntu-toolchain-r-test

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - if [[ -n "$GCC_VERSION" ]]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

before_install:
  - rm -rf dist *.egg-info && python setup.py sdist

install: skip
script:
  - ci/cpp_test.sh "${cmake_option}"
  - ci/python_test.sh

deploy:
  on:
    tags: true
  provider: pypi
  user: bbp.opensource
  skip_existing: true
  password:
    secure: "Es1muWW5O7DtgOznhQmgZmPjpFCeCE9lJjVM7mjXMeOO7ENRVHIssH3zLXewgBDrtSmaCPVO4SF1b2jO4kFOo3NV65b6+1tGcKnaN53VPbOF5Na5cevxZxY63znRy4y8P8PtTkuFS3JGx9x0KBuFyH+oT0t6J3JFCWyhV4EArDXbouNMLu+i2nL5fC8wl1TLWVA38zjbloqXwai4P3osJ/IRGkvmAW8na4g5ygovYTfFdCkGViTnnmJo1KITIin3rNgQHA/wghMH+lvEhYeis6fCfHPPV/1LMmVCEFi1lTmPimON4+zPP6WB9e/8jpoQCXivmkTuLsEvxVRiMfP5j06KjSMyjmSDKTSLaFUGnsykmcCU5vQAcy6WZNujnH6p0WfMrMRV9dR0oDs2QZIFfgbTHOWLZGI1jSujlR8goHlCFTIPd7fCjLJ4VqHAV+f2eTWLd1v//CXTAw1ivrwdIO4mBo6zGcH0rQRPDaY5xyspvmoX9RtsLugfnPYEePhI0xA+xU1GK/7BA738Yru8N9Q4zkOth4jVLHisN5p/gQuiu0j5WUCIfXp1CVgcFb6iiEQ83I0deI3rspcpK17OGqdanU9fWccRsxqFyqmQisWEexMLOlbKYKKatfP2PZR7wmCk8cYnL1A7GrBCEmcOCP460rmGHqsDfGyYo6FImFM="
