language: python

git:
  depth: false

addons: &gcc7
  apt:
    packages:
      - g++-7
      - libhdf5-dev
      - hdf5-tools
    sources:
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
    - env: GCC_VERSION=7
      dist: xenial
      sudo: required
      python: 3.6
      addons: *gcc7
    - os: linux
    - env: GCC_VERSION=7
      dist: xenial
      sudo: required
      python: 2.7
      addons: *gcc7

    - os: osx
      osx_image: xcode10.3
      language: generic
      python: 3.6
      addons: *os
        homebrew:
          packages:
            - hdf5
    - os: osx
      osx_image: xcode10.3
      language: generic
      python: 2.7
      addons:
        homebrew:
          packages:
            - hdf5

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi

before_install:
  - rm -rf dist *.egg-info && python setup.py sdist

install: skip
script:
  - ci/cpp_test.sh
  - ci/python_test.sh


deploy:
  on:
    tags: true
  provider: pypi
  user: bbp.opensource
  skip_existing: true
  password:
    secure: "Es1muWW5O7DtgOznhQmgZmPjpFCeCE9lJjVM7mjXMeOO7ENRVHIssH3zLXewgBDrtSmaCPVO4SF1b2jO4kFOo3NV65b6+1tGcKnaN53VPbOF5Na5cevxZxY63znRy4y8P8PtTkuFS3JGx9x0KBuFyH+oT0t6J3JFCWyhV4EArDXbouNMLu+i2nL5fC8wl1TLWVA38zjbloqXwai4P3osJ/IRGkvmAW8na4g5ygovYTfFdCkGViTnnmJo1KITIin3rNgQHA/wghMH+lvEhYeis6fCfHPPV/1LMmVCEFi1lTmPimON4+zPP6WB9e/8jpoQCXivmkTuLsEvxVRiMfP5j06KjSMyjmSDKTSLaFUGnsykmcCU5vQAcy6WZNujnH6p0WfMrMRV9dR0oDs2QZIFfgbTHOWLZGI1jSujlR8goHlCFTIPd7fCjLJ4VqHAV+f2eTWLd1v//CXTAw1ivrwdIO4mBo6zGcH0rQRPDaY5xyspvmoX9RtsLugfnPYEePhI0xA+xU1GK/7BA738Yru8N9Q4zkOth4jVLHisN5p/gQuiu0j5WUCIfXp1CVgcFb6iiEQ83I0deI3rspcpK17OGqdanU9fWccRsxqFyqmQisWEexMLOlbKYKKatfP2PZR7wmCk8cYnL1A7GrBCEmcOCP460rmGHqsDfGyYo6FImFM="
